# Generated by Django 3.0.5 on 2020-04-09 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='author',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='text',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='title',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('1buy', 'Buy'), ('2sell', 'Sell'), ('3trade', 'Trade'), ('4transfer', 'Transfer'), ('5earned', 'Earned')], default='1buy', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_in_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_in_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='currency_in_type', to='currency.Currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_out_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_out_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='currency_out_type', to='currency.Currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='fee_type', to='currency.Currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=None),
        ),
    ]
