# Generated by Django 3.0.5 on 2020-04-09 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20200408_2237'),
        ('transaction', '0003_auto_20200408_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency_in_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency_out_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fee_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_in_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_out_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('1buy', 'Buy'), ('2sell', 'Sell'), ('3trade', 'Trade'), ('4transfer', 'Transfer'), ('5earn', 'Earn')], default='1buy', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_in_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='currency_in_type', to='currency.Currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_out_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='currency_out_type', to='currency.Currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_type', to='currency.Currency'),
        ),
    ]
