# Generated by Django 3.0.5 on 2020-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20200408_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency_in_quantity',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_out_quantity',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_quantity',
            field=models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=40, null=True, verbose_name='Quantity'),
        ),
    ]
