# Generated by Django 3.0.5 on 2020-04-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_auto_20200413_2134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set(),
        ),
    ]
